### ISSUE TITLE
Undefined method error: session[:user_id]

### ISSUE THREAD

**Issue by Ishmaru** [Ishmaru/indie_think_tank#2]
![screen shot 2016-06-08 at 7 13 58 am](https://cloud.githubusercontent.com/assets/18603064/15897277/c1f42328-2d48-11e6-896b-3ad40968e5c1.png)
##### In models/game.rb

```
  before_save :assign_user
```

```
private
 def assign_user
   self.user_id ||= session[:user_id]
 end
```

Games are nested under Ideas, As many games belong to an Idea, However the User who owns the Idea and the User who created the Idea are different Users. So nesting users/id/ideas/id/games/new is not logical.
### To test,

log in as (Ishmaru) 1234, and navigate to an idea, either from the root of ideas/index, and click Make this a game, enter all fields, and submit.
### Attempts to fix:

I tried using the current_user method from application controller, moved assign_user definition outside private, I also tried:
##### In controllers/games_controller.rb

```
def create
    @user = session[:user_id]
    @idea = Idea.find(params[:idea_id])
    @game = @idea.games.new (game_params)
    if @game.save
...
```

^ This results in no error, however the user_id of the game is set to nil.

**Comment by ezRAez** [comment]
## WHAT A GREAT ISSUE!

So we have a few problems here.

First, `session` and `params` do not exist in the model, so we can't access that in `Game.rb`.

Another issue: in Rails, when we set things to self in the model with that `||=`, we're actually building using methods.

Look at the method above:

``` ruby
    def default_description
      self.description ||= summary
    end
```

This is like saying `self.description ||= self.summary`. `.summary`, `.description` and `.description=` are methods on the Game instance!

Therefore, it's giving you this "undefined method error" because it's like you're calling to `@game.session`, which of course, doesn't exist on Game.

Now, I know what you're thinking: _"Ezra, this is great info, but tell me how to fix this freakin error!"_

You should set your `@game.user` in the controller, and you shouldn't do it through sessions.

In the create, you should do this:

``` ruby
def create
    @idea = Idea.find(params[:idea_id])
    @game = @idea.games.new (game_params)
    @game.user = current_user
    if @game.save
    …
```

We're now accessing our current_user object and setting it as the Game instance's user!

If you want to have this variable for users other than the current_user, and you have a nested route (I didn't check) you could also do:

`@game.user_id = params[:user_id]`

Let me know if it still doesn't work!

**Comment by Ishmaru** [comment]
@game.user = current_user works now! Thank you. Its a little hard to wrap my head around when it's appropriate to use session[:id] and current_user. I understand one is a value and one is a method, but in the case of @game.user = session[:id] returning nil, while current_user method returns the appropriate value. However when comparing game.user_id == current_user, is wrong and have to use game.user_id == session[:id]. Its pretty confusing at times.

**Comment by ezRAez** [comment]
This is because current_user is an object (an instance of the User model), and user_id is an integer (the literal id of the user).

Comparing them will never come up the same, but current_user.id == @user.user_id _could_ come up true, bc they're both integers.

**Comment by ghost** [comment]
They're both objects. One is a User object, one is an Integer (FixNum) object. Apples and oranges.

**Comment by Ishmaru** [comment]
I thought that if I compared with a method that method would be invoked and the value returned by that method is what would be used in that comparison.

**Comment by ezRAez** [comment]
correct! however, the method you invoke is returning an Integer (FixNum) object, not a User object. If you'd like to check the user associated with game, you can simply say `@game.user`.

Hope that clears it up a bit!

**Comment by Ishmaru** [comment]
I believe I get it now. Thank you!
